- name: Backup Cisco routers
  include_playbook: backup.yml

- name: Gather Cisco facts
  include_playbook: cisco_facts.yml

- name: Setup GRE Tunnel
  include_playbook: gre.yml

- name: Setup Routing
  include_playbook: router_configs.yml
