- name: Backup Cisco routers
  import_playbook: backup.yml

- name: Gather Cisco facts
  import_playbook: cisco_facts.yml

- name: Setup GRE Tunnel
  import_playbook: gre.yml

- name: Setup Routing on Ciscos
  import_playbook: router_configs.yml

- name: Update routing locally
  import_playbook: host_routes.yml
