- name: backup router configurations
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:

  - name: backup router configuration
    ios_config:
      lines:
        banner motd % You have been pwned by the Urban Seagulls Hackers Collective. %
