- name: Simple banner hack message
  hosts: cisco
  connection: network_cli
  gather_facts: no

  tasks:

  - name: set the banner hack message
    ios_config:
      lines:
        banner motd % You have been pwned by the Urban Seagulls Hackers Collective. %
