---
- name: Router Configurations
  hosts: routers
  gather_facts: no
  connection: network_cli

  vars:
    ansible_network_os: ios
    dns_servers:
      - 8.8.8.8
      - 8.8.4.4
    host1_private_ip: "{{ hostvars['host1']['private_ip'] }}"
    control_private_ip: "{{ hostvars['ansible']['private_ip'] }}"

  tasks:

    - name: configure router rtr1
      block:

      - name: Static route from R1 to R2
        ios_static_route:
          prefix: "{{ host1_private_ip }}"
          mask: 255.255.255.255
          next_hop: 10.0.0.2

      - name: configure name servers
        ios_system:
          name_servers: "{{ item }}"
        with_items: "{{ dns_servers }}"

      when:
        - '"rtr1" in inventory_hostname'

    - name: configure router rtr2
      block:

      - name: enable GigabitEthernet1 interface
        ios_interface:
          name: GigabitEthernet1
          description: interface to host1
          state: present

      - name: dhcp configuration for GigabitEthernet1
        ios_config:
          lines:
            - ip address dhcp
          parents: interface GigabitEthernet1

      - name: Static route from R2 to R1
        ios_static_route:
          prefix: "{{ control_private_ip }}"
          mask: 255.255.255.255
          next_hop: 10.0.0.1

      - name: configure name servers
        ios_system:
          name_servers: "{{ item }}"
        with_items: "{{ dns_servers }}"

      when:
        - '"rtr2" in inventory_hostname'

import_playbook: host-routes.yml          
